### ISSUE TITLE
Create a simple GPU implementation for the NCC computation

### ISSUE THREAD

**Issue by benvanwerkhoven** [nlesc-sherlock/cluster-analysis#15]
The NFI already created a highly optimized GPU implementation. Therefore this is something that is not essential. But since we do not have their source code, it would be nice to have a working implementation of our own. In case we have to recompute some of the NCC scores or aim to compute scores for bigger datasets. And nonetheless it is very nice exercise for anybody who wants to get more experienced with GPU Computing.

**Comment by HannoSpreeuw** [comment]
Would be great for my CUDA programming skills!

**Comment by HannoSpreeuw** [comment]
But I am not much of a Java person.

**Comment by benvanwerkhoven** [comment]
Fortunately the Java part is only the boilerplate host code which you can mostly copy/paste from the other parts of the application, so that won't be too much of a problem. Also I can help out with any Java problems you run into.

**Comment by HannoSpreeuw** [comment]
Cool!

**Comment by benvanwerkhoven** [comment]
I just found out that apparently you can not assign multiple people to an issue, that's a pity.

**Comment by benvanwerkhoven** [comment]
Great slide deck about optimizing reduce operations: https://docs.nvidia.com/cuda/samples/6_Advanced/reduction/doc/reduction.pdf

**Comment by benvanwerkhoven** [comment]
This has been implemented with great success. The GPU implementation is 14.5 times faster, including data transfers.
