### ISSUE TITLE
See if we can do without FFTs in the PCE computation

### ISSUE THREAD

**Issue by benvanwerkhoven** [nlesc-sherlock/cluster-analysis#3]
I am suspecting that the FFTs that are used within the PCE computations are actually unnecessary. Currently the pattern are only real-valued and I think it may be possible to compute a cross correlation of two real-valued signals without using FFTs, but I would like someone with more knowledge on the subject to look into this.

**Comment by jspaaks** [comment]
maybe you can do something similar to what Rob is doing in his pulsar stuff, i.e. stack signals of a predefined wavelength?

**Comment by anandgavai** [comment]
Hi All,
Thanks for all the emails Ben ;-) !
Exciting days to start tomorrow.

Specifically I could contribute to
#4 (distance matrix)
#5 (evaluation of this measure following up from #4)
#6 (heuristics, mainly graph based)
#9 (other algorithms, we could consider using bayesian networks ? )

It is indeed a pity that we can have more than one person per task, in
principle I am open to other tasks as well that would expands my horizon
;-).

Regards,
Anand

**Comment by benvanwerkhoven** [comment]
Thanks to the work of Sonja and Anand we now fully understand how PCE works and what is computed at all the intermediate steps. They have shown that the FFTs are necessary for computing the PCE scores. And therefore this issue can be closed.
